services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-app:latest
    container_name: frontend-container
    restart: unless-stopped
    networks:
      - public-network
      - internal-network
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VUE_APP_API_URL=http://backend:8081
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/momo-store/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-app:latest
    container_name: backend-container
    restart: on-failure
    networks:
      - internal-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8081/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M

networks:
  public-network:
    driver: bridge
  internal-network:
    driver: bridge
    internal: true
